package de.schuetzmarvin.caspprovidermod;

public enum ValuesEnum {
    IP_ADDRESS,MAC_ADDRESS,VENDOR,PORT_ID,PORT_PROTOCOL,PORT_STATUS,PORT_SERVICE_NAME,PASSWORD,USERNAME,ORDER_NUMBER,FIRMWARE_REVISION, NEWIP_ADDRESS, DICTIONARY, PLC_TYP
}
